apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  schemaVersion: v1.0.0
  name: ruby-bandwidth-iris
  description: |-
    Ruby SDK for Bandwidth Phone Number Dashboard (AKA: Dashboard, Iris)
  annotations:
    github.com/project-slug: Bandwidth/ruby-bandwidth-iris
    organization: BW
    costCenter: Development - Software Infra
spec:
  type: Library
  owner: github/band-swi
  lifecycle: production
