name: Deploy SDK

on:
  release:
    types:
      - published
  push:

jobs:
  deploy:
    name: Deploy to Rubygems
    
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: Install Packages
      run: bundle install

    - name: Test
      run: rake
      
    - name: Deploy to Rubygems
      run: |
        #mkdir ~/.gem #Rubygems needs this directory for auth
        #echo "---\n:rubygems_api_key: $RUBYGEMS_API_KEY" > ~/.gem/credentials #The file to store rubygems auth. Must be in this format
        #chmod 0600 ~/.gem/credentials #Rubygems expects this permissions
        #gem build *.gemspec
        #gem push *.gem -k rubygems
        echo "test to make sure this runs"
      env:
          RUBYGEMS_API_KEY: ${{ secrets.rubygems-api-key }}
      shell: sh

    - uses: Bandwidth/build-notify-slack-action@v1.0.0
      if: always()
      with:
        job-status: ${{ job.status }}
        slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
        slack-channel: ${{ secrets.SLACK_CHANNEL }}
